language: php

php:
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer install

script:
  - vendor/bin/ecs check --config=ecs.yml .
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry vendor/bin/php-coveralls -v
